#!/usr/bin/env bash
# build-zshrc.sh — concatenate shell/parts/*.zsh into dist/zshrc
# The dist file is what the remote bootstrap fallback fetches, so users
# without a local clone get the same modular content as a single file.
set -euo pipefail

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
PARTS_DIR="$REPO_ROOT/shell/parts"
DIST_DIR="$REPO_ROOT/dist"
OUT="$DIST_DIR/zshrc"

mkdir -p "$DIST_DIR"

{
  echo "# ============================================================="
  echo "# AUTO-GENERATED by scripts/build-zshrc.sh — DO NOT EDIT BY HAND"
  echo "# Source modules live under shell/parts/"
  echo "# ============================================================="
  echo
  for f in "$PARTS_DIR"/*.zsh; do
    echo "# --- $(basename "$f") ---"
    cat "$f"
    echo
  done
  echo '# Per-machine overrides (not version-controlled)'
  echo '[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"'
  echo
  echo 'echo "✅ Loaded custom zshrc (dist)"'
} > "$OUT"

echo "✅ Wrote $OUT ($(wc -l <"$OUT") lines)"
