apiVersion: v1
kind: Pod
metadata:
  name: devenv
  labels:
    app: busybox
spec:
  containers:
  - image: starcry/devenv
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always

